swagger.yml
https://europace.atlassian.net/browse/KITT-97
=> KITT-97 #dosimeta_geburtsland #Geburtsland des Antragstellers aufgenommen

README.md
https://europace.atlassian.net/browse/KITT-80
=> KITT-80 #dosimeta-dok-antwortzeit #Antwortzeiterwartung ergänzt.

beispiele/example-annahme.md
Schlusswerte im Tilgungsplan korrigiert.
https://europace.atlassian.net/browse/KITT-89
=> #dosimeta-response-dok #KITT-89 Dokument in der Beispielresponse ergänzt

README.md, beispiele/example-annahme-erfolgreich.md, beispiele/example-annahme-mit-downselling.md, beispiele/example-annahme-mit-fehlenden-daten.md, beispiele/example-annahme-mit-unterdeckung.md, swagger.yml
Doku erweitert.
https://europace.atlassian.net/browse/KITT-100
=> KITT-100 #dosimeta_further_examples #Weitere Beispielanfragen und -antworten aufgenommen

beispiele/example-annahme-erfolgreich.md, beispiele/example-annahme-mit-downselling.md, beispiele/example-annahme-mit-fehlenden-daten.md, beispiele/example-annahme-mit-unterdeckung.md, swagger.yml
Breaking Change in Absprache mit VB., 
https://europace.atlassian.net/browse/KITT-149
=> #KITT-149 #Renaming ausgaben to monatlicheAusgaben. 

beispiele/example-annahme-erfolgreich.md, beispiele/example-annahme-mit-downselling.md, beispiele/example-annahme-mit-fehlenden-daten.md, beispiele/example-annahme-mit-unterdeckung.md, swagger.yml
=> KITT-196 tag to tilgungsplaneintrag added

README.md, beispiele/example-annahme-erfolgreich.md, beispiele/example-annahme-mit-downselling.md, beispiele/example-annahme-mit-fehlenden-daten.md, beispiele/example-annahme-mit-unterdeckung.md, swagger.yml
- some advices and example labels added to swagger file
- update message-labels in request/response-examples 
- no breaking change
https://europace.atlassian.net/jira/software/projects/KITT/boards/28?selectedIssue=KITT-208
=> #KITT-208 update documentation

.github/release-drafter.yml, .github/workflows/release.yaml
Ich habe hier den release-drafter analog zu den anderen APIs hinzugefügt (siehe tactical spannung)
=> Add release workflow

swagger.yml
Die PartnerId ist immer vorhanden.
Die Firma wird vererbt.
Anrede, Vor- und Nachname würde ich als vorhanden voraussetzen auch wenn das PM hier alle Zustände erlaubt.
https://europace.atlassian.net/browse/KITT-710?atlOrigin=eyJpIjoiMTAyM2ZlMjMwZjcyNDdmZjk0ZTBmNWNjZWE1YWFmNTYiLCJwIjoiaiJ9
=> #KITT-710 mark kundenbetreuer fields partnerId,firma,vorname,nachname and anrede as required

swagger.yml
https://europace.atlassian.net/browse/KITT-640?atlOrigin=eyJpIjoiOGJkMTU0N2NlOWFlNGM3MjkwOTZkM2E1MzQ4ZmQ3OWIiLCJwIjoiaiJ9
=> #KITT-640 remove versicherer from api, due to already used versichererIds

swagger.yml
- also marked required antragstellerId for identifikation type
=> remove old versicherer

README.md, beispiele/example-annahme-erfolgreich.md, beispiele/example-annahme-mit-downselling.md, beispiele/example-annahme-mit-fehlenden-daten.md, beispiele/example-annahme-mit-unterdeckung.md, beispiele/example-technischer-fehler-antwort-annahme.md, swagger.yml
@gomil Mit Blick auf das Issue https://github.com/europace/kex-market-engine-api/issues/12 bin ich jetzt auch hin- und hergerissen. Hab auch kein Schmerz das auf String + Doku umzubauen. Aus API Sicht ist es aber so schon schöner.
=> #KITT-1207 #APISMART-671 add vertriebskanal (B2B, B2B2C) to annahme request. cleanup readme.

README.md, beispiele/example-annahme-erfolgreich.md, swagger.yml
Ich habe mich hier an der BSK ME API orientiert. Ein Beispiel habe ich erweitert, ich hoffe, das ist einizgermaßen klar so wie es ist.
Außerdem versucht, die ReadMe bzgl. der Anpasser und was wir tatsächlich schicken zu verbessern.
=> KITT-1555 #ProduktanbieterParameter (Partnerkennzeichen) hinzugefügt

README.md
At some points, I wasn't 100 percent sure if I should translate the words such as "machbar" into "feasible" - open for discussions. Same for other Fachwörter.
=> Translate KEX-ME-API to 🇬🇧 

README.md
=> Exchange "broker" by "agent"

README.md
Klarer herausgestellt, dass auch ein nicht-machbares Angebot vollständig sein muss.
=> ReadMe verbessert

README.md, beispiele/example-annahme-mit-kontoumsaetzen.md, swagger.yml
- List of account statements added to request
- Each account statements knows its applicant
- Example added
=> KITT-2621 #account statements added

README.md
Added information about the use of account statements
=> Readme extended

swagger.yml
- added anrede DIVERS (version 3.1.0)
=> KITT-3338 #added anrede DIVERS

.github/CODEOWNERS, .github/dependabot.yml, .github/workflows/release.yaml, swagger.yml
- use dependabot for github action updates
- use commit hash to fix version for github actions
- fix typos in descriptions
=> GitHub Actions

swagger.yml
=> Auszahlungsbetrag als Provisionsbasis fuer Versicherungen
